// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

use super::render;
use crate::model::Package;
use serde_json::{json, Value};
use std::path::PathBuf;

fn package(value: Value) -> Package {
    serde_json::from_value(value).unwrap()
}

fn fixture() -> Value {
    json!({
        "schema_version": 1,
        "clients": [],
        "models": [{
            "name": "Widget", "cross_language_id": null, "doc": "A widget.",
            "fields": [
                {"name":"next", "wire_name":"nextWidget", "type":{"kind":"model","name":"Widget"},
                 "optional":true,"read_only":false,"doc":null},
                {"name":"type", "wire_name":"@type", "type":{"kind":"string"},
                 "optional":false,"read_only":false,"doc":"The widget kind."},
                {"name":"items", "wire_name":"Items", "type":{"kind":"array","value_type":{"kind":"enum","name":"Color"}},
                 "optional":false,"read_only":true,"doc":null}
            ]
        }],
        "enums": [{
            "name":"Color","cross_language_id":null,"extensible":true,
            "values":[{"name":"Red","wire_value":"red"},{"name":"Blue","wire_value":"azure-blue"}]
        }]
    })
}

fn file(files: &std::collections::BTreeMap<PathBuf, String>, name: &str) -> String {
    files[&PathBuf::from(name)].clone()
}

#[test]
fn emits_modules_models_and_wire_enums() {
    let files = render(&package(fixture())).unwrap();
    assert_eq!(files.len(), 4);
    for contents in files.values() {
        assert!(contents
            .lines()
            .take(5)
            .any(|line| { line == "// Code generated by generate_client. DO NOT EDIT." }));
    }
    assert!(file(&files, "mod.rs").contains("pub mod models;"));
    assert!(file(&files, "models/mod.rs").contains("pub use enums::*;"));
    let models = file(&files, "models/models.rs");
    assert!(models.contains("pub r#type: String"));
    assert!(models.contains("rename = \"@type\""));
    assert!(models.contains("pub next: Option<Box<Widget>>"));
    assert!(models.contains("rename = \"nextWidget\""));
    assert!(models.contains("skip_serializing_if = \"Option::is_none\""));
    assert!(models.contains("pub items: Vec<Color>"));
    assert!(models.contains("skip_serializing"));
    assert!(models.contains("SafeDebug"));
    let enums = file(&files, "models/enums.rs");
    assert!(enums.contains("UnknownValue(String)"));
    assert!(enums.contains("\"azure-blue\""));
    assert!(enums.contains("impl<'de> Deserialize<'de> for Color"));
    assert!(enums.contains("Self::UnknownValue(value.to_owned())"));
    assert!(enums.contains("Self::UnknownValue(value) => value.as_str()"));
    assert!(enums.contains("serializer.serialize_str(self.as_ref())"));
    assert!(enums.contains("SafeDebug"));
}

#[test]
fn deterministic_across_input_order() {
    let original = fixture();
    let mut reversed = original.clone();
    reversed["models"][0]["fields"]
        .as_array_mut()
        .unwrap()
        .reverse();
    reversed["enums"][0]["values"]
        .as_array_mut()
        .unwrap()
        .reverse();
    assert_eq!(
        render(&package(original)).unwrap(),
        render(&package(reversed)).unwrap()
    );
}

#[test]
fn refuses_clients_and_operations() {
    let mut input = fixture();
    input["clients"] = json!([{
        "name":"WidgetClient","parent":null,"cross_language_id":null,
        "doc":null,"endpoint_name":"endpoint","operations":[],
        "children":[]
    }]);
    assert!(render(&package(input))
        .unwrap_err()
        .contains("client WidgetClient"));
}

#[test]
fn rejects_invalid_identifiers_and_unsupported_wire_types() {
    let mut input = fixture();
    input["models"][0]["fields"][0]["name"] = json!("bad-name");
    assert!(render(&package(input))
        .unwrap_err()
        .contains("Widget.bad-name"));

    let mut input = fixture();
    input["models"][0]["fields"][0]["type"] = json!({"kind":"bytes"});
    assert!(render(&package(input))
        .unwrap_err()
        .contains("explicit wire encoding"));

    let mut input = fixture();
    input["models"][0]["fields"][0]["type"] = json!({"kind":"utcDateTime"});
    assert!(render(&package(input))
        .unwrap_err()
        .contains("explicit wire format"));
}

#[test]
fn rejects_collisions_and_ambiguous_optionals() {
    let mut input = fixture();
    input["models"][0]["fields"][0]["wire_name"] = json!("Items");
    assert!(render(&package(input)).unwrap_err().contains("duplicate"));

    let mut input = fixture();
    input["models"][0]["fields"][0]["type"] =
        json!({"kind":"nullable","value_type":{"kind":"model","name":"Widget"}});
    assert!(render(&package(input))
        .unwrap_err()
        .contains("missing/null semantics"));

    let mut input = fixture();
    input["enums"][0]["values"][0]["name"] = json!("UnknownValue");
    assert!(render(&package(input)).unwrap_err().contains("fallback"));
}

#[test]
fn boxes_only_recursive_direct_references() {
    let mut input = fixture();
    input["models"][0]["fields"][0]["type"] =
        json!({"kind":"array","value_type":{"kind":"model","name":"Widget"}});
    let models = file(&render(&package(input)).unwrap(), "models/models.rs");
    assert!(models.contains("pub next: Option<Vec<Widget>>"));
    assert!(!models.contains("Box<Widget>"));
}

#[test]
fn boxes_mutual_cycles_and_requires_nullable_presence() {
    let mut input = fixture();
    input["models"][0]["fields"][0]["optional"] = json!(false);
    input["models"][0]["fields"][0]["type"] =
        json!({"kind":"nullable","value_type":{"kind":"model","name":"Sibling"}});
    input["models"].as_array_mut().unwrap().push(json!({
        "name":"Sibling","cross_language_id":null,"doc":null,
        "fields":[{"name":"widget","wire_name":"widget","type":{"kind":"model","name":"Widget"},
                   "optional":true,"read_only":false,"doc":null}]
    }));
    let models = file(&render(&package(input)).unwrap(), "models/models.rs");
    assert!(models.contains("pub widget: Option<Widget>"));
    assert!(models.contains("pub next: Option<Box<Sibling>>"));
    assert!(models.contains("deserialize_with = \"Option::deserialize\""));
}

#[test]
fn fixed_enum_rejects_unknown_wire_value() {
    let mut input = fixture();
    input["enums"][0]["extensible"] = json!(false);
    let enums = file(&render(&package(input)).unwrap(), "models/enums.rs");
    assert!(enums.contains("unknown_variant"));
    assert!(!enums.contains("UnknownValue(String)"));
}

#[test]
fn rejects_duplicate_enum_wire_values() {
    let mut input = fixture();
    input["enums"][0]["values"][1]["wire_value"] = json!("red");
    assert!(render(&package(input))
        .unwrap_err()
        .contains("duplicate wire enum value"));
}
