[workspace]
resolver = "2"
members = [
  "check_api_superset",
  "generate_api",
  "generate_client",
]

[workspace.package]
authors = ["Microsoft"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Azure/azure-sdk-for-rust"
rust-version = "1.95"

[workspace.dependencies]
clap = { version = "4.5.58", features = ["derive"] }
quote = "1.0.44"
rustdoc-types = "0.57.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
syn = { version = "2.0.115", features = ["full"] }
toml = "0.8.20"
wasmtime = { version = "=44.0.3", default-features = false, features = ["component-model", "cranelift", "runtime", "std"] }
wasmtime-wasi = { version = "=44.0.3", default-features = false, features = ["p2"] }
