// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

//! Rust source file emitter.
//!
//! Transforms the code model into Rust source files under `src/generated/`.

use anyhow::Result;
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::{fs, path::Path};
use typespec_codegen_types as model;

/// Emit all generated source files for a crate.
pub fn emit_crate(krate: &model::Crate, output_dir: &Path) -> Result<()> {
    let gen_dir = output_dir.join("src").join("generated");

    emit_mod_rs(krate, &gen_dir)?;
    emit_clients_mod(krate, &gen_dir)?;
    emit_models_mod(krate, &gen_dir)?;

    for client in &krate.clients {
        emit_client(client, krate, &gen_dir)?;
    }

    emit_models(krate, &gen_dir)?;
    emit_enums(krate, &gen_dir)?;

    // Emit lib.rs
    let lib_rs = "// Copyright (c) Microsoft Corporation. All rights reserved.\n\
         // Licensed under the MIT License.\n\
         //\n\
         // Code generated by Microsoft (R) Rust Code Generator.\n\
         \n\
         #![cfg_attr(docsrs, feature(doc_cfg))]\n\
         \n\
         mod generated;\n\
         pub use generated::*;\n"
        .to_string();
    fs::write(output_dir.join("src").join("lib.rs"), lib_rs)?;

    Ok(())
}

fn emit_mod_rs(krate: &model::Crate, gen_dir: &Path) -> Result<()> {
    let mut content = String::from(generated_header());

    content.push_str("/// Clients used to communicate with the service.\n");
    content.push_str("pub mod clients;\n");
    content
        .push_str("/// Contains all the data structures and types used by the client library.\n");
    content.push_str("pub mod models;\n");

    // Re-export the main client
    if let Some(main_client) = krate.clients.first() {
        content.push_str(&format!(
            "pub use clients::{{{name}, {name}Options}};\n",
            name = main_client.name
        ));
    }

    fs::write(gen_dir.join("mod.rs"), content)?;
    Ok(())
}

fn emit_clients_mod(krate: &model::Crate, gen_dir: &Path) -> Result<()> {
    let mut content = String::from(generated_header());

    for client in &krate.clients {
        let module_name = client.name.to_snake_case();
        content.push_str(&format!("mod {module_name};\n"));
    }
    for client in &krate.clients {
        let module_name = client.name.to_snake_case();
        content.push_str(&format!("pub use {module_name}::*;\n"));
    }

    fs::write(gen_dir.join("clients").join("mod.rs"), content)?;
    Ok(())
}

fn emit_models_mod(krate: &model::Crate, gen_dir: &Path) -> Result<()> {
    let mut content = String::from(generated_header());

    if !krate.models.is_empty() {
        content.push_str("mod models;\n");
        content.push_str("pub use models::*;\n");
    }
    if !krate.enums.is_empty() {
        content.push_str("mod enums;\n");
        content.push_str("pub use enums::*;\n");
    }

    fs::write(gen_dir.join("models").join("mod.rs"), content)?;
    Ok(())
}

fn emit_client(client: &model::Client, _krate: &model::Crate, gen_dir: &Path) -> Result<()> {
    let module_name = client.name.to_snake_case();
    let mut content = String::from(generated_header());

    content.push_str("use azure_core::{\n");
    content.push_str("    credentials::TokenCredential,\n");
    content.push_str("    fmt::SafeDebug,\n");
    content.push_str("    http::{\n");
    content.push_str("        policies::{auth::BearerTokenAuthorizationPolicy, Policy},\n");
    content.push_str("        ClientOptions, Pipeline, Url,\n");
    content.push_str("    },\n");
    content.push_str("    tracing, Result,\n");
    content.push_str("};\n");
    content.push_str("use std::sync::Arc;\n\n");

    // Client struct
    if let Some(doc) = &client.doc {
        content.push_str(&format!("/// {doc}\n"));
    }
    content.push_str("#[tracing::client]\n");
    content.push_str(&format!("pub struct {} {{\n", client.name));
    content.push_str("    pub(crate) api_version: String,\n");
    content.push_str("    pub(crate) endpoint: Url,\n");
    content.push_str("    pub(crate) pipeline: Pipeline,\n");
    for param in &client.parameters {
        content.push_str(&format!(
            "    pub(crate) {}: {},\n",
            param.name,
            type_ref_to_rust(&param.param_type)
        ));
    }
    content.push_str("}\n\n");

    // Options struct
    content.push_str(&format!(
        "/// Options used when creating a [`{name}`]({name})\n",
        name = client.name
    ));
    content.push_str("#[derive(Clone, SafeDebug)]\n");
    content.push_str(&format!("pub struct {}Options {{\n", client.name));
    content.push_str("    pub api_version: String,\n");
    content.push_str("    pub client_options: ClientOptions,\n");
    content.push_str("}\n\n");

    // Sub-client accessors
    if !client.sub_clients.is_empty() {
        content.push_str(&format!("impl {} {{\n", client.name));
        for sub in &client.sub_clients {
            content.push_str(&format!(
                "    /// Returns a new instance of {}.\n",
                sub.client_name
            ));
            content.push_str("    #[tracing::subclient]\n");
            content.push_str(&format!(
                "    pub fn {}(&self) -> {} {{\n",
                sub.accessor_name, sub.client_name
            ));
            content.push_str(&format!("        {} {{\n", sub.client_name));
            content.push_str("            api_version: self.api_version.clone(),\n");
            content.push_str("            endpoint: self.endpoint.clone(),\n");
            content.push_str("            pipeline: self.pipeline.clone(),\n");
            for param in &client.parameters {
                content.push_str(&format!(
                    "            {name}: self.{name}.clone(),\n",
                    name = param.name
                ));
            }
            content.push_str("        }\n");
            content.push_str("    }\n\n");
        }
        content.push_str("}\n");
    }

    fs::write(
        gen_dir.join("clients").join(format!("{module_name}.rs")),
        content,
    )?;
    Ok(())
}

fn emit_models(krate: &model::Crate, gen_dir: &Path) -> Result<()> {
    if krate.models.is_empty() {
        return Ok(());
    }

    let mut content = String::from(generated_header());
    content.push_str("use azure_core::fmt::SafeDebug;\n");
    content.push_str("use serde::{Deserialize, Serialize};\n");
    content.push_str("use std::collections::HashMap;\n\n");

    for model in &krate.models {
        if let Some(doc) = &model.doc {
            content.push_str(&format!("/// {doc}\n"));
        }
        content.push_str("#[derive(Clone, Default, Deserialize, SafeDebug, Serialize)]\n");
        content.push_str(&format!("pub struct {} {{\n", model.name));
        for field in &model.fields {
            if let Some(doc) = &field.doc {
                content.push_str(&format!("    /// {doc}\n"));
            }
            let rust_type = type_ref_to_rust(&field.field_type);
            let final_type = if field.optional {
                format!("Option<{rust_type}>")
            } else {
                rust_type
            };
            if field.name != field.serialized_name {
                content.push_str(&format!(
                    "    #[serde(rename = \"{}\")]\n",
                    field.serialized_name
                ));
            }
            content.push_str(&format!("    pub {}: {final_type},\n", field.name));
        }
        content.push_str("}\n\n");
    }

    fs::write(gen_dir.join("models").join("models.rs"), content)?;
    Ok(())
}

fn emit_enums(krate: &model::Crate, gen_dir: &Path) -> Result<()> {
    if krate.enums.is_empty() {
        return Ok(());
    }

    let mut content = String::from(generated_header());
    content.push_str("use serde::{Deserialize, Serialize};\n\n");

    for e in &krate.enums {
        if let Some(doc) = &e.doc {
            content.push_str(&format!("/// {doc}\n"));
        }
        content.push_str("#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]\n");
        content.push_str(&format!("pub enum {} {{\n", e.name));
        for value in &e.values {
            if let Some(doc) = &value.doc {
                content.push_str(&format!("    /// {doc}\n"));
            }
            let variant_name = value.name.to_upper_camel_case();
            if let Some(s) = value.value.as_str() {
                if s != variant_name {
                    content.push_str(&format!("    #[serde(rename = \"{s}\")]\n"));
                }
            }
            content.push_str(&format!("    {variant_name},\n"));
        }
        if e.extensible {
            content.push_str("    #[serde(untagged)]\n    UnknownValue(serde_json::Value),\n");
        }
        content.push_str("}\n\n");
    }

    fs::write(gen_dir.join("models").join("enums.rs"), content)?;
    Ok(())
}

fn type_ref_to_rust(type_ref: &model::TypeRef) -> String {
    match type_ref {
        model::TypeRef::Scalar(s) => scalar_to_rust(s).to_string(),
        model::TypeRef::Model { name }
        | model::TypeRef::Enum { name }
        | model::TypeRef::Union { name } => name.clone(),
        model::TypeRef::Array { element } => format!("Vec<{}>", type_ref_to_rust(element)),
        model::TypeRef::Map { key, value } => {
            format!(
                "HashMap<{}, {}>",
                type_ref_to_rust(key),
                type_ref_to_rust(value)
            )
        }
        model::TypeRef::Option { inner } => format!("Option<{}>", type_ref_to_rust(inner)),
    }
}

fn scalar_to_rust(s: &model::ScalarType) -> &'static str {
    match s {
        model::ScalarType::Bool => "bool",
        model::ScalarType::I32 => "i32",
        model::ScalarType::I64 => "i64",
        model::ScalarType::F32 => "f32",
        model::ScalarType::F64 => "f64",
        model::ScalarType::String => "String",
        model::ScalarType::Bytes => "Vec<u8>",
        model::ScalarType::DateTime => "time::OffsetDateTime",
        model::ScalarType::Url => "azure_core::http::Url",
        model::ScalarType::Uuid => "String",
    }
}

fn generated_header() -> &'static str {
    "// Copyright (c) Microsoft Corporation. All rights reserved.\n\
     // Licensed under the MIT License.\n\
     //\n\
     // Code generated by Microsoft (R) Rust Code Generator. DO NOT EDIT.\n\n"
}
