// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

mod clients;
mod enums;
mod models;
mod types;

use crate::model::Package;
use quote::quote;
use std::{
    collections::BTreeMap,
    io::Write,
    path::PathBuf,
    process::{Command, Stdio},
};
use syn::Ident;

const HEADER: &str = "// Copyright (c) Microsoft Corporation. All rights reserved.\n\
// Licensed under the MIT License.\n\
// Code generated by generate_client. DO NOT EDIT.\n\n";

/// Render the model-only schema-2 slice with paths relative to `src/generated`.
pub(crate) fn render(package: &Package) -> Result<BTreeMap<PathBuf, String>, String> {
    render_preview(package, false)
}

/// Render the guarded basic-client slice with paths relative to `src/generated`.
pub(crate) fn render_basic(package: &Package) -> Result<BTreeMap<PathBuf, String>, String> {
    render_preview(package, true)
}

fn render_preview(package: &Package, basic: bool) -> Result<BTreeMap<PathBuf, String>, String> {
    package.validate()?;
    if let Some(client) = package.clients.first().filter(|_| !basic) {
        return Err(format!(
            "client {}: client and operation emission is not supported (model-only slice)",
            client.name
        ));
    }
    for name in package
        .models
        .iter()
        .map(|model| model.name.as_str())
        .chain(
            package
                .enums
                .iter()
                .map(|enumeration| enumeration.name.as_str()),
        )
    {
        if matches!(
            name,
            "String"
                | "Option"
                | "Vec"
                | "Box"
                | "Result"
                | "SafeDebug"
                | "Serialize"
                | "Deserialize"
                | "Serializer"
                | "Deserializer"
        ) {
            return Err(format!(
                "type {name}: collides with a generated Rust type or import"
            ));
        }
    }
    let recursive = types::recursive_fields(&package.models);
    let enum_export = (!package.enums.is_empty()).then(|| {
        quote!(
            pub use enums::*;
        )
    });
    let model_export = (!package.models.is_empty()).then(|| {
        quote!(
            pub use models::*;
        )
    });
    let client_export = (!package.clients.is_empty()).then(|| {
        quote!(
            pub mod clients;
        )
    });
    let mut rendered = vec![
        (
            "mod.rs",
            quote! {
                /// Contains all the data structures and types used by the client library.
                pub mod models;
                #client_export
            },
        ),
        (
            "models/mod.rs",
            quote! {
                mod enums;
                #[allow(clippy::module_inception)]
                mod models;
                #enum_export
                #model_export
            },
        ),
        ("models/models.rs", models::render(package, &recursive)?),
        ("models/enums.rs", enums::render(package)?),
    ];
    if basic && !package.clients.is_empty() {
        rendered.push(("clients.rs", clients::render(package)?));
    }
    let mut files = BTreeMap::new();
    for (path, tokens) in rendered {
        let source = format!("{HEADER}{tokens}\n");
        syn::parse_file(&source).map_err(|error| format!("{path}: invalid Rust: {error}"))?;
        let formatted = format_rust(&source, path)?;
        syn::parse_file(&formatted)
            .map_err(|error| format!("{path}: rustfmt produced invalid Rust: {error}"))?;
        files.insert(PathBuf::from(path), formatted);
    }
    Ok(files)
}

fn format_rust(source: &str, path: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("{path}: failed to launch rustfmt: {error}"))?;
    child
        .stdin
        .take()
        .ok_or_else(|| format!("{path}: rustfmt stdin unavailable"))?
        .write_all(source.as_bytes())
        .map_err(|error| format!("{path}: rustfmt stdin: {error}"))?;
    let output = child
        .wait_with_output()
        .map_err(|error| format!("{path}: rustfmt: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "{path}: rustfmt failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|error| format!("{path}: rustfmt UTF-8: {error}"))
}

fn ident(name: &str, scope: &str) -> Result<Ident, String> {
    if let Ok(ident) = syn::parse_str::<Ident>(name) {
        return Ok(ident);
    }
    syn::parse_str::<Ident>(&format!("r#{name}"))
        .map_err(|_| format!("{scope}: invalid Rust identifier '{name}'"))
}

fn field_ident(name: &str, scope: &str) -> Result<Ident, String> {
    let chars: Vec<_> = name.chars().collect();
    let mut rust_name = String::new();
    for (index, &ch) in chars.iter().enumerate() {
        if ch == '_' || ch == '-' {
            if !rust_name.ends_with('_') {
                rust_name.push('_');
            }
        } else if ch.is_ascii_uppercase() {
            let previous = index.checked_sub(1).and_then(|i| chars.get(i));
            let next = chars.get(index + 1);
            if !rust_name.is_empty()
                && !rust_name.ends_with('_')
                && (previous
                    .is_some_and(|value| value.is_ascii_lowercase() || value.is_ascii_digit())
                    || previous.is_some_and(char::is_ascii_uppercase)
                        && next.is_some_and(char::is_ascii_lowercase))
            {
                rust_name.push('_');
            }
            rust_name.push(ch.to_ascii_lowercase());
        } else if ch.is_ascii_lowercase() || ch.is_ascii_digit() {
            rust_name.push(ch);
        } else {
            return Err(format!("{scope}: unsupported Rust field name '{name}'"));
        }
    }
    ident(&rust_name, scope)
}

#[cfg(test)]
mod tests;
