// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

use std::{
    collections::BTreeMap,
    fs,
    path::{Component, Path, PathBuf},
};

pub(crate) fn reconcile(
    crate_dir: &Path,
    files: &BTreeMap<PathBuf, String>,
    check: bool,
) -> Result<(), String> {
    if files.is_empty() {
        return Err("Generator produced no Rust source files".to_string());
    }
    let generated = crate_dir.join("src").join("generated");
    validate_parent(&generated)?;
    for (relative, contents) in files {
        if relative.as_os_str().is_empty()
            || relative
                .extension()
                .is_none_or(|extension| extension != "rs")
            || !relative
                .components()
                .all(|part| matches!(part, Component::Normal(_)))
        {
            return Err(format!(
                "Invalid generated file path: {}",
                relative.display()
            ));
        }
        let file = generated.join(relative);
        validate_parent(
            file.parent()
                .ok_or_else(|| format!("Generated file has no parent: {}", file.display()))?,
        )?;
        if file.is_symlink() {
            return Err(format!("Generated file is a symlink: {}", file.display()));
        }
        if check {
            let existing = fs::read_to_string(&file)
                .map_err(|error| format!("{}: {error}", file.display()))?;
            if normalize_lines(&existing) != normalize_lines(contents) {
                return Err(format!("Generated output differs: {}", file.display()));
            }
        } else if file.exists() {
            let existing = fs::read_to_string(&file)
                .map_err(|error| format!("{}: {error}", file.display()))?;
            if !existing
                .lines()
                .take(5)
                .any(|line| line.contains("Code generated by"))
            {
                return Err(format!(
                    "Refusing to overwrite a file without a generated-code marker: {}",
                    file.display()
                ));
            }
        }
    }
    if generated.is_dir() {
        check_extra_owned_files(&generated, &generated, files)?;
    }
    if !check {
        for (relative, contents) in files {
            let file = generated.join(relative);
            let parent = file
                .parent()
                .ok_or_else(|| format!("Generated file has no parent: {}", file.display()))?;
            fs::create_dir_all(parent).map_err(|error| format!("{}: {error}", parent.display()))?;
            fs::write(&file, contents).map_err(|error| format!("{}: {error}", file.display()))?;
        }
    }
    Ok(())
}

fn check_extra_owned_files(
    root: &Path,
    directory: &Path,
    files: &BTreeMap<PathBuf, String>,
) -> Result<(), String> {
    for entry in
        fs::read_dir(directory).map_err(|error| format!("{}: {error}", directory.display()))?
    {
        let entry = entry.map_err(|error| format!("{}: {error}", directory.display()))?;
        let path = entry.path();
        if entry
            .file_type()
            .map_err(|error| format!("{}: {error}", path.display()))?
            .is_symlink()
        {
            return Err(format!(
                "Symlink under generated source: {}",
                path.display()
            ));
        }
        if path.is_dir() {
            check_extra_owned_files(root, &path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            let relative = path
                .strip_prefix(root)
                .map_err(|error| format!("{}: {error}", path.display()))?;
            if !files.contains_key(relative) {
                let contents = fs::read_to_string(&path)
                    .map_err(|error| format!("{}: {error}", path.display()))?;
                if contents
                    .lines()
                    .take(5)
                    .any(|line| line.contains("Code generated by"))
                {
                    return Err(format!("Unexpected generated source: {}", path.display()));
                }
            }
        }
    }
    Ok(())
}

fn normalize_lines(text: &str) -> String {
    text.replace("\r\n", "\n").replace('\r', "\n")
}

fn validate_parent(path: &Path) -> Result<(), String> {
    for parent in path.ancestors() {
        if parent.is_symlink() {
            return Err(format!(
                "Generated path contains a symlink: {}",
                parent.display()
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests;
