// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

use std::{
    collections::BTreeMap,
    fs,
    io::ErrorKind,
    path::{Component, Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

static NEXT_STAGING: AtomicU64 = AtomicU64::new(0);

pub(crate) fn reconcile(
    crate_dir: &Path,
    files: &BTreeMap<PathBuf, String>,
    check: bool,
) -> Result<(), String> {
    reconcile_with_hook(crate_dir, files, check, |_| Ok(()))
}

fn reconcile_with_hook(
    crate_dir: &Path,
    files: &BTreeMap<PathBuf, String>,
    check: bool,
    mut before_install: impl FnMut(&Path) -> Result<(), String>,
) -> Result<(), String> {
    if files.is_empty() {
        return Err("Generator produced no Rust source files".to_string());
    }
    let generated = crate_dir.join("src").join("generated");
    validate_parent(&generated)?;
    for (relative, contents) in files {
        if relative.as_os_str().is_empty()
            || relative
                .extension()
                .is_none_or(|extension| extension != "rs")
            || !relative
                .components()
                .all(|part| matches!(part, Component::Normal(_)))
        {
            return Err(format!(
                "Invalid generated file path: {}",
                relative.display()
            ));
        }
        let file = generated.join(relative);
        preflight_destination(&file, !check)?;
        if check {
            let existing = fs::read_to_string(&file)
                .map_err(|error| format!("{}: {error}", file.display()))?;
            if normalize_lines(&existing) != normalize_lines(contents) {
                return Err(format!("Generated output differs: {}", file.display()));
            }
        }
    }
    if generated.is_dir() {
        check_extra_owned_files(&generated, &generated, files)?;
    }
    if !check {
        let staging = Staging::new(&crate_dir.join("src"))?;
        let result = (|| {
            for (relative, contents) in files {
                let staged = staging.path.join("new").join(relative);
                let parent = staged.parent().ok_or_else(|| {
                    (
                        format!("Staged file has no parent: {}", staged.display()),
                        false,
                    )
                })?;
                fs::create_dir_all(parent)
                    .map_err(|error| (format!("{}: {error}", parent.display()), false))?;
                fs::write(&staged, contents)
                    .map_err(|error| (format!("{}: {error}", staged.display()), false))?;
            }
            commit_staged(&generated, files, &staging.path, &mut before_install)
        })();
        let retain = result
            .as_ref()
            .is_err_and(|(_, rollback_failed)| *rollback_failed);
        let cleanup = staging.cleanup(retain);
        if let Err((error, _)) = result {
            return Err(match cleanup {
                Ok(()) => error,
                Err(cleanup) => format!("{error}; cleanup failed: {cleanup}"),
            });
        }
        cleanup?;
    }
    Ok(())
}

fn preflight_destination(file: &Path, overwrite: bool) -> Result<(), String> {
    let parent = file
        .parent()
        .ok_or_else(|| format!("Generated file has no parent: {}", file.display()))?;
    validate_parent(parent)?;
    for directory in parent.ancestors() {
        if directory.exists() && !directory.is_dir() {
            return Err(format!(
                "Generated parent is not a directory: {}",
                directory.display()
            ));
        }
    }
    match fs::symlink_metadata(file) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() {
                return Err(format!("Generated file is a symlink: {}", file.display()));
            }
            if !metadata.is_file() {
                return Err(format!("Generated path is not a file: {}", file.display()));
            }
            if overwrite {
                let existing = fs::read_to_string(file)
                    .map_err(|error| format!("{}: {error}", file.display()))?;
                if !existing
                    .lines()
                    .take(5)
                    .any(|line| line.contains("Code generated by"))
                {
                    return Err(format!(
                        "Refusing to overwrite a file without a generated-code marker: {}",
                        file.display()
                    ));
                }
            }
        }
        Err(error) if error.kind() == ErrorKind::NotFound => {}
        Err(error) => return Err(format!("{}: {error}", file.display())),
    }
    Ok(())
}

struct Staging {
    path: PathBuf,
    src: PathBuf,
    created_src: bool,
}

impl Staging {
    fn new(src: &Path) -> Result<Self, String> {
        validate_parent(src)?;
        let created_src = if src.exists() {
            if !src.is_dir() {
                return Err(format!(
                    "Generated parent is not a directory: {}",
                    src.display()
                ));
            }
            false
        } else {
            fs::create_dir(src).map_err(|error| format!("{}: {error}", src.display()))?;
            true
        };
        for _ in 0..100 {
            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let path = src.join(format!(
                ".generate-client-staging-{}-{nonce}-{}",
                std::process::id(),
                NEXT_STAGING.fetch_add(1, Ordering::Relaxed)
            ));
            match fs::create_dir(&path) {
                Ok(()) => {
                    return Ok(Self {
                        path,
                        src: src.to_path_buf(),
                        created_src,
                    })
                }
                Err(error) if error.kind() == ErrorKind::AlreadyExists => continue,
                Err(error) => {
                    if created_src {
                        let _ = fs::remove_dir(src);
                    }
                    return Err(format!("{}: {error}", path.display()));
                }
            }
        }
        if created_src {
            let _ = fs::remove_dir(src);
        }
        Err(format!(
            "Could not create unique staging directory under {}",
            src.display()
        ))
    }

    fn cleanup(self, retain: bool) -> Result<(), String> {
        if retain {
            return Ok(());
        }
        fs::remove_dir_all(&self.path)
            .map_err(|error| format!("{}: {error}", self.path.display()))?;
        if self.created_src {
            match fs::remove_dir(&self.src) {
                Ok(()) => {}
                Err(error) if error.kind() == ErrorKind::DirectoryNotEmpty => {}
                Err(error) => return Err(format!("{}: {error}", self.src.display())),
            }
        }
        Ok(())
    }
}

struct Change {
    destination: PathBuf,
    backup: PathBuf,
    backed_up: bool,
    installed: bool,
}

fn commit_staged(
    generated: &Path,
    files: &BTreeMap<PathBuf, String>,
    staging: &Path,
    mut before_install: impl FnMut(&Path) -> Result<(), String>,
) -> Result<(), (String, bool)> {
    for relative in files.keys() {
        preflight_destination(&generated.join(relative), true).map_err(|error| (error, false))?;
    }
    let mut changes = Vec::new();
    let mut created_dirs = Vec::new();
    let result = (|| {
        for (index, relative) in files.keys().enumerate() {
            let destination = generated.join(relative);
            let parent = destination.parent().ok_or_else(|| {
                format!("Generated file has no parent: {}", destination.display())
            })?;
            let missing: Vec<_> = parent.ancestors().take_while(|dir| !dir.exists()).collect();
            for dir in missing.into_iter().rev() {
                validate_parent(dir)?;
                fs::create_dir(dir).map_err(|error| format!("{}: {error}", dir.display()))?;
                created_dirs.push(dir.to_path_buf());
            }
            preflight_destination(&destination, true)?;
            let backup = staging.join("backups").join(index.to_string());
            changes.push(Change {
                destination: destination.clone(),
                backup: backup.clone(),
                backed_up: false,
                installed: false,
            });
            if destination.exists() {
                fs::create_dir_all(staging.join("backups"))
                    .map_err(|error| format!("{}: {error}", staging.display()))?;
                fs::rename(&destination, &backup)
                    .map_err(|error| format!("{}: {error}", destination.display()))?;
                changes.last_mut().unwrap().backed_up = true;
            }
        }
        for (relative, change) in files.keys().zip(changes.iter_mut()) {
            validate_parent(change.destination.parent().ok_or_else(|| {
                format!(
                    "Generated file has no parent: {}",
                    change.destination.display()
                )
            })?)?;
            match fs::symlink_metadata(&change.destination) {
                Ok(_) => {
                    return Err(format!(
                        "Generated destination became occupied: {}",
                        change.destination.display()
                    ))
                }
                Err(error) if error.kind() == ErrorKind::NotFound => {}
                Err(error) => return Err(format!("{}: {error}", change.destination.display())),
            }
            let destination = &change.destination;
            before_install(destination)?;
            let staged = staging.join("new").join(relative);
            fs::rename(&staged, destination).map_err(|error| {
                format!("{} -> {}: {error}", staged.display(), destination.display())
            })?;
            change.installed = true;
        }
        Ok::<(), String>(())
    })();
    if let Err(error) = result {
        let mut rollback_errors = Vec::new();
        for change in changes.iter().rev() {
            if let Some(parent) = change.destination.parent() {
                if let Err(failure) = validate_parent(parent) {
                    rollback_errors.push(failure);
                    continue;
                }
            }
            if change.installed {
                if let Err(failure) = fs::remove_file(&change.destination) {
                    rollback_errors.push(format!("{}: {failure}", change.destination.display()));
                    continue;
                }
            }
            if change.backed_up {
                if change.destination.exists() || change.destination.is_symlink() {
                    rollback_errors.push(format!(
                        "Rollback destination occupied: {}",
                        change.destination.display()
                    ));
                } else if let Err(failure) = fs::rename(&change.backup, &change.destination) {
                    rollback_errors.push(format!(
                        "{} -> {}: {failure}",
                        change.backup.display(),
                        change.destination.display()
                    ));
                }
            }
        }
        for dir in created_dirs.iter().rev() {
            if let Some(parent) = dir.parent() {
                if let Err(failure) = validate_parent(parent) {
                    rollback_errors.push(failure);
                    continue;
                }
            }
            if let Err(failure) = fs::remove_dir(dir) {
                rollback_errors.push(format!("{}: {failure}", dir.display()));
            }
        }
        if rollback_errors.is_empty() {
            return Err((error, false));
        }
        return Err((
            format!(
                "{error}; rollback failed: {}; backups retained at {}",
                rollback_errors.join("; "),
                staging.display()
            ),
            true,
        ));
    }
    Ok(())
}

fn check_extra_owned_files(
    root: &Path,
    directory: &Path,
    files: &BTreeMap<PathBuf, String>,
) -> Result<(), String> {
    for entry in
        fs::read_dir(directory).map_err(|error| format!("{}: {error}", directory.display()))?
    {
        let entry = entry.map_err(|error| format!("{}: {error}", directory.display()))?;
        let path = entry.path();
        if entry
            .file_type()
            .map_err(|error| format!("{}: {error}", path.display()))?
            .is_symlink()
        {
            return Err(format!(
                "Symlink under generated source: {}",
                path.display()
            ));
        }
        if path.is_dir() {
            check_extra_owned_files(root, &path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            let relative = path
                .strip_prefix(root)
                .map_err(|error| format!("{}: {error}", path.display()))?;
            if !files.contains_key(relative) {
                let contents = fs::read_to_string(&path)
                    .map_err(|error| format!("{}: {error}", path.display()))?;
                if contents
                    .lines()
                    .take(5)
                    .any(|line| line.contains("Code generated by"))
                {
                    return Err(format!("Unexpected generated source: {}", path.display()));
                }
            }
        }
    }
    Ok(())
}

fn normalize_lines(text: &str) -> String {
    text.replace("\r\n", "\n").replace('\r', "\n")
}

fn validate_parent(path: &Path) -> Result<(), String> {
    for parent in path.ancestors() {
        if parent.is_symlink() {
            return Err(format!(
                "Generated path contains a symlink: {}",
                parent.display()
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests;
