// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

use super::reconcile;
use std::{
    collections::BTreeMap,
    fs,
    path::{PathBuf, MAIN_SEPARATOR},
    sync::atomic::{AtomicUsize, Ordering},
};

static NEXT_TEST: AtomicUsize = AtomicUsize::new(0);
const GENERATED: &str =
    "// Copyright (c) Microsoft Corporation. All rights reserved.\n// Code generated by generate_client. DO NOT EDIT.\n";

struct TestDirectory(PathBuf);

impl TestDirectory {
    fn new() -> Self {
        let path = std::env::temp_dir().join(format!(
            "generate-client-output-{}-{}",
            std::process::id(),
            NEXT_TEST.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir(&path).unwrap();
        Self(path)
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.0).unwrap();
    }
}

#[test]
fn writes_only_expected_paths_and_checks_existing_content() {
    let dir = TestDirectory::new();
    let files = BTreeMap::from([(
        PathBuf::from("models").join("mod.rs"),
        GENERATED.to_string(),
    )]);
    assert!(reconcile(&dir.0, &files, true)
        .unwrap_err()
        .contains("mod.rs"));
    reconcile(&dir.0, &files, false).unwrap();
    reconcile(&dir.0, &files, true).unwrap();
    fs::write(dir.0.join("src/generated/models/mod.rs"), "handwritten").unwrap();
    assert!(reconcile(&dir.0, &files, false)
        .unwrap_err()
        .contains("Refusing"));
    assert_eq!(
        fs::read_to_string(dir.0.join("src/generated/models/mod.rs")).unwrap(),
        "handwritten"
    );
}

#[test]
fn rejects_parent_traversal() {
    let dir = TestDirectory::new();
    let files = BTreeMap::from([(
        PathBuf::from(format!("..{MAIN_SEPARATOR}lib.rs")),
        String::new(),
    )]);
    assert!(reconcile(&dir.0, &files, false)
        .unwrap_err()
        .contains("Invalid generated file path"));
    assert!(!dir.0.join("src/lib.rs").exists());
}

#[test]
fn detects_handwritten_conflicts_before_writing_any_output() {
    let dir = TestDirectory::new();
    let generated = dir.0.join("src/generated");
    fs::create_dir_all(&generated).unwrap();
    fs::write(generated.join("z.rs"), "handwritten").unwrap();
    let files = BTreeMap::from([
        (PathBuf::from("a.rs"), GENERATED.to_string()),
        (PathBuf::from("z.rs"), GENERATED.to_string()),
    ]);
    assert!(reconcile(&dir.0, &files, false)
        .unwrap_err()
        .contains("Refusing"));
    assert!(!generated.join("a.rs").exists());
}

#[test]
fn rejects_unexpected_owned_files_but_preserves_handwritten_files() {
    let dir = TestDirectory::new();
    let generated = dir.0.join("src/generated");
    fs::create_dir_all(&generated).unwrap();
    fs::write(generated.join("custom.rs"), "handwritten").unwrap();
    let files = BTreeMap::from([(PathBuf::from("mod.rs"), GENERATED.to_string())]);
    reconcile(&dir.0, &files, false).unwrap();
    fs::write(generated.join("old.rs"), GENERATED).unwrap();
    assert!(reconcile(&dir.0, &files, true)
        .unwrap_err()
        .contains("Unexpected generated source"));
    assert!(generated.join("custom.rs").exists());
}

#[test]
fn check_ignores_line_ending_differences() {
    let dir = TestDirectory::new();
    let files = BTreeMap::from([(PathBuf::from("mod.rs"), GENERATED.to_string())]);
    reconcile(&dir.0, &files, false).unwrap();
    let path = dir.0.join("src/generated/mod.rs");
    fs::write(&path, GENERATED.replace('\n', "\r\n")).unwrap();
    reconcile(&dir.0, &files, true).unwrap();
}
